#!/bin/bash

source ./input_domain.lib
source ./subdomain_enumeration.lib
source ./dirsearch.lib

input_Domain
subdomain_Enumeration 
printf "subdomain enumeration is done ..."
dirsearch_Fuzzing
printf "dir searching done .. "
